import { StyleSheet } from "react-native";

export const heroesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1e1e2f",
    paddingTop: 12,
    paddingHorizontal: 12,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#f0f0f0",
    marginBottom: 12,
    textAlign: "center",
  },
  input: {
    width: "100%",
    height: 40,
    backgroundColor: "#2b2c3b",
    borderRadius: 8,
    paddingHorizontal: 12,
    color: "#f0f0f0",
    marginBottom: 12,
  },
  grid: {
    justifyContent: "center",
  },
  card: {
    width: 80,
    height: 88,
    alignItems: "center",
    margin: 6,
    backgroundColor: "#2b2c3b",
    borderRadius: 8,
    padding: 6,
  },
  image: {
    width: 64,
    height: 36,
    borderRadius: 6,
    marginBottom: 6,
  },
  name: {
    color: "#f0f0f0",
    fontSize: 12,
    textAlign: "center",
  },
  botbar: {
    height: 40,
    marginTop: 20,
    backgroundColor: "#111",
    width: "100%",
  },
  details: {
    marginTop: 24,
  },
  heroName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#f0f0f0",
    marginBottom: 8,
  },
  heroImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginBottom: 16,
  },
  subsection: {
    marginBottom: 0,
    width: "100%",
    maxWidth: 600,
  },
  subTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#f0f0f0",
    marginBottom: 8,
    marginTop: 16,
    textAlign: "center",
  },
  synergyGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 1,
  },
  synergyItem: {
    width: "15%",
    alignItems: "center",
    marginBottom: 12,
    marginHorizontal: 6,
  },
  partnerImage: {
    width: 60,
    height: 60,
    borderRadius: 6,
    marginBottom: 4,
  },
  positive: {
    color: "#4caf50",
    fontWeight: "bold",
  },
  negative: {
    color: "#f44336",
    fontWeight: "bold",
  },
  loreSection: {
    paddingHorizontal: 12,
    marginTop: 16,
    marginBottom: 32,
    maxWidth: 600,
    minWidth: 200,
  },
  loreText: {
    color: "#f0f0f0",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
    fontStyle: "italic",
  },
  scrollContainer: {
    alignItems: "center",
    marginTop: 24,
    marginBottom: 32,
    paddingHorizontal: 12,
  },

  scrollCurveTop: {
    width: "100%",
    maxWidth: 600,
    height: 24,
    backgroundColor: "#f5f0dc",
    borderTopLeftRadius: 60,
    borderTopRightRadius: 60,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    marginBottom: -12,
    zIndex: 1,
  },

  scrollBody: {
    backgroundColor: "#f5f0dc",
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: "#d2b48c",
    paddingVertical: 28,
    paddingHorizontal: 20,
    width: "100%",
    maxWidth: 600,
    zIndex: 0,
  },

  scrollCurveBottom: {
    width: "100%",
    maxWidth: 600,
    height: 24,
    backgroundColor: "#f5f0dc",
    borderBottomLeftRadius: 60,
    borderBottomRightRadius: 60,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    marginTop: -12,
    zIndex: 1,
  },

  scrollText: {
    color: "#3e2f1c",
    fontSize: 14,
    lineHeight: 22,
    fontStyle: "italic",
    textAlign: "justify",
  },
});
